### ISSUE TITLE
Snow won't melt under trees in summer with serene seasons

### ISSUE THREAD

**Issue by StormChaserBoy** [IMB11/SnowUnderTrees#22] opened 2024-10-10 18:10 UTC
I have serene seasons 10.1.0.1 and snow under trees 2.5.3 and running MC 1.21.1 (fabric). Snow would generate under trees in the winter but would not melt in the summer. Also there is a lot of input lag sometimes when it's raining coming from this mod.

**Comment by IMB11** [comment] 2024-10-24 17:26
Duplicate of #19

**Closed by IMB11** 2024-10-24 17:26 UTC
